version: "2"
services:
  server:
    container_name: "server"
    command: npm run dev
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - TZ=Asia/Taipei

  client:
    container_name: "client"
    build: ./client
    ports:
      - "3001:80"
    volumes:
      - ./client/html:/usr/share/nginx/html

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  db:
    container_name: "db"
    build: ./db/
    environment:
      TZ: "Asia/Taipei"
      MYSQL_USER: "mysql_user"
      MYSQL_PASSWORD: "mysql_password"
      MYSQL_ROOT_PASSWORD: "mysql_password"
      MYSQL_DATABASE: "my-db"
    ports:
      - "3306:3306"
    command: [
            '--default-time-zone=+8:00'
    ]